### ISSUE TITLE
This project doesn't work

### ISSUE THREAD

**Issue by zpq0724** [paschal533/Opensea-clone#1]
This project doesn't work

**Comment by paschal533** [comment]
Hello
Can you be more specific on the part that isn't working for you... Send me the error message you are getting :)

**Comment by paschal533** [comment]
> This project doesn't work

Hello
Can you be more specific on the part that isn't working for you... Send me the error message you are getting :)

**Comment by zpq0724** [comment]
when i run npm install and  then  npm start,
The code reports an error and the page cannot be seen correctly.
error about process and  appId













At 2022-01-10 19:48:29, "Paschal" ***@***.***> wrote:

This project doesn't work

Hello
Can you be more specific on the part that isn't working for you... Send me the error message you are getting :)

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by paschal533** [comment]
You need to do more than that to be able to start this project
I have added everything you need to do to run this project in the Readme file, follow the instructions there thoroughly and you will be able to start this project... Enjoy

**Comment by zpq0724** [comment]
thans
