### ISSUE TITLE
No Smart Contract Details Provided. Please deploy smart contract and provide address + ABI in the MoralisDappProvider.js file

### ISSUE THREAD

**Issue by jiemodetang** [paschal533/Opensea-clone#2]
“No Smart Contract Details Provided. Please deploy smart contract and provide address + ABI in the MoralisDappProvider.js file”

how can i use  my moralisServers increase  address + ABI to test

**Comment by paschal533** [comment]
You have to deploy the smart contract then add the address and ABI you got from smart contract  to MoralisDappProvider.js file before starting the App.
